separate step for tf validate

diff --git a/.github/workflows/terraform_run.yml b/.github/workflows/terraform_run.yml
--- a/.github/workflows/terraform_run.yml
+++ b/.github/workflows/terraform_run.yml
@@ -40,7 +40,11 @@ jobs:
       - name: Terraform format and validate
         run: |
           terraform fmt -check
-          terraform validate
+
+      # run regardless of previous step failing
+      - name: Terraform validate
+        if: success() || failure()
+        run: terraform validate -no-color
 
       - name: Run terraform plan
         run: |
